# Generated by Django 5.0.2 on 2024-03-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="date",
            field=models.DateField(verbose_name="post date"),
        ),
    ]
