# Generated by Django 5.0.2 on 2024-03-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blogpage_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpage",
            name="date",
        ),
    ]
