# Generated by Django 5.0.2 on 2024-03-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_blogpage_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="post date"),
        ),
    ]
