# Generated by Django 5.0.2 on 2024-03-28 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_homepage_body"),
        ("wagtailcore", "0091_remove_revision_submitted_for_moderation"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="hero",
            field=models.CharField(
                blank=True,
                help_text="Text to display on CTA",
                max_length=200,
                verbose_name="Hero CTA",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_link",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose a Link",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Hero CTA Link",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
