# Generated by Django 5.0.2 on 2024-03-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Navigation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instagram", models.URLField(blank=True, verbose_name="Twitter URL")),
                ("github", models.URLField(blank=True, verbose_name="Github URL")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
